version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5431:5432"
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SCHIPHOL_AIRPORT_DB
    networks:
      - app-network

networks:
  app-network:
    name: app-network