name: Data engineering assignment test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build app"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          make install

  lint-test:
    name: 'Check format'
    runs-on: ubuntu-latest
    needs: [build]

    steps:    
      - uses: actions/checkout@v3
      
      - name: Check code formatting
        run: |
          make check_format
  
  unit-test:
    name: 'Unit testing'
    runs-on: ubuntu-latest
    needs: [build, lint-test]

    steps:      
      - uses: actions/checkout@v3

      - name: Run tests
        env:
          SCHIPHOL_API_APP_ID: ${{ secrets.SCHIPHOL_API_APP_ID }}
          SCHIPHOL_API_APP_KEY: ${{ secrets.SCHIPHOL_API_APP_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: SCHIPHOL_AIRPORT_DB
          DB_PREFIX: postgresql
          DB_IP_ADDRESS: postgres
        run: |
          make test

  docker_build_push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [lint-test, unit-test]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true  # Push only on push to main branch
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/etl_service:latest
            ${{ secrets.DOCKER_USERNAME }}/etl_service:${{ github.sha }}