name: Data engineering assignment test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  unit-test:
    name: 'Unit testing'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: SCHIPHOL_AIRPORT_DB

    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          make install
          
      - name: Run tests
        env:
          SCHIPHOL_API_APP_ID: ${{ secrets.SCHIPHOL_API_APP_ID }}
          SCHIPHOL_API_APP_KEY: ${{ secrets.SCHIPHOL_API_APP_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: SCHIPHOL_AIRPORT_DB
          DB_PREFIX: postgresql
          DB_IP_ADDRESS: postgres
        run: |
          make test

  build-docker:
    name: 'Build and deploy Docker image'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build Docker image
        run: |
          docker build -t etl_service .

      - name: Push to Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag etl_service:latest ${{ secrets.DOCKER_USERNAME }}/etl_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/etl_service:latest

      - name: Run Docker container
        env:
          SCHIPHOL_API_APP_ID: ${{ secrets.SCHIPHOL_API_APP_ID }}
          SCHIPHOL_API_APP_KEY: ${{ secrets.SCHIPHOL_API_APP_KEY }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: SCHIPHOL_AIRPORT_DB
          DB_PREFIX: postgresql
          DB_IP_ADDRESS: postgres:5432
        run: |
          docker run -p 5000:5000 \
            --network="host" \
            -e SCHIPHOL_API_APP_ID=${{ secrets.SCHIPHOL_API_APP_ID }} \
            -e SCHIPHOL_API_APP_KEY=${{ secrets.SCHIPHOL_API_APP_KEY }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=SCHIPHOL_AIRPORT_DB \
            -e DB_PREFIX=postgresql \
            -e DB_IP_ADDRESS=postgres:5432 \
            etl_service:latest
